theme: jekyll-theme-hacker
name: blog
description: Software and Security
github:
  is_project_page: false
footer-links:
  dribbble:
  email: shawn at lungdart[.]net
  facebook:
  flickr:
  github: lungdart
  instagram:
  linkedin: shawn-boutilier
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
exclude:
  - LICENSE
  - CNAME
