theme: jekyll-theme-midnight
name: blog
description: Software and Security
footer-links:
  dribbble:
  email: shawn at lungdart[.]net
  facebook:
  flickr:
  github: lungdart
  instagram:
  linkedin: shawn-boutilier
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
exclude:
  - LICENSE
  - CNAME
